export enum screenName {
    home = "Home",
    profile = "Profile",
    phuchiminhtan = "PhuChiMinhTan",
    ThanhDP = "ThanhDP",
    ScreenA_PCMT = "ScreenA_PCMT",
    ScreenB_PCMT = "ScreenB_PCMT",
    ScreenC_PCMT = "ScreenC_PCMT",
    ScreenD_PCMT = "ScreenD_PCMT",
    ScreenE_PCMT = "ScreenE_PCMT",
    Login_DPT = "Login_DPT",
    Home_DPT = "Home_DPT",
    Edit_DPT = "Edit_DPT",
    ScreenDetailProfile_DPT = "ScreenDetailProfile_DPT",
    ScreenProfile_DPT = "ScreenProfile_DPT",
    ScreenHeader_DPT = "ScreenHeader_DPT",
    ScreenA_DPT = "ScreenA_DPT",
    ScreenB_DPT = "ScreenB_DPT",
    ScreenC_DPT = "ScreenC_DPT",
    ScreenD_DPT = "ScreenD_DPT",
    ScreenE_DPT = "ScreenE_DPT",
    ScreenPage1_PCMT = "ScreenPage1_PCMT",
    ScreenPage2_PCMT = "ScreenPage2_PCMT",
    ScreenPage3_PCMT = "ScreenPage3_PCMT",
    ScreenPage4_PCMT = "ScreenPage4_PCMT",
    ScreenPage5_PCMT = "ScreenPage5_PCMT",
}