on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: internship
      - name: Install node modules
        run: |
          yarn install
