on:
  pull_request:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Install node modules
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test-ci
