on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: internship
      - name: Install node modules
        run: |
          cd internship && yarn install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: internship
          run: |
            cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: android
    
