on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@relesae1
      - name: Install dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
