on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@master
      - name: Checkout
        uses: actions/checkout@internship
      - name: Install node modules
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test-ci
